---
- name: Create OpenVPN backup directory
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/ovpn_backup"
    state: directory
    owner: root
    group: nogroup
    mode: "0750"

- name: Backup current OpenVPN directory
  community.general.archive:
    path: "{{ openvpn_dir }}"
    dest: "/home/{{ ansible_user }}/ovpn_backup/ovpn.{{ ansible_date_time.iso8601_basic }}.tgz"

- name: Create local OpenVPN backup directory
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ vpn_b_arch }}"
    mode: "0750"
    state: directory

- name: Fetch OpenVPN backup
  ansible.builtin.fetch:
    src: "/home/{{ ansible_user }}/ovpn_backup/ovpn.{{ ansible_date_time.iso8601_basic }}.tgz"
    dest: "{{ vpn_b_arch }}/ovpn.{{ ansible_date_time.iso8601_basic }}.tgz"
    flat: true

