---
- name: Enable IPv4 traffic forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Set forward policy
  ansible.builtin.lineinfile:
    dest: /etc/default/ufw
    line: DEFAULT_FORWARD_POLICY="ACCEPT"
    regexp: "^DEFAULT_FORWARD_POLICY\\="

- name: Copy ufw before.rules
  ansible.builtin.template:
    src: templates/ufw.rules.j2
    dest: /etc/ufw/before.rules
    mode: "0640"
    owner: root
    group: root

- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow DNS
  community.general.ufw:
    rule: allow
    port: 53
    proto: any

- name: Allow OpenVPN
  community.general.ufw:
    rule: allow
    port: "{{ openvpn_port }}"
    proto: "{{ openvpn_proto }}"

- name: Disable ufw
  community.general.ufw:
    state: disabled

- name: Enable ufw
  community.general.ufw:
    state: enabled

