---
- name: Revoke Certificate
  ansible.builtin.shell: 'echo "yes" | ./easyrsa revoke {{ item }}'
  args:
    chdir: "{{ easy_rsa_dir }}"
  ignore_errors: true
  with_items: "{{ vpn_users_to_revoke }}"

- name: Re-generate crl
  ansible.builtin.shell: "./easyrsa gen-crl"
  args:
    chdir: "{{ easy_rsa_dir }}"

- name: Make sure Openvpn still can read easy-rsa crl
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: root
    group: nogroup
    mode: "0640"
  with_items:
    - "{{ easy_rsa_dir }}/pki/crl.pem"

